# Generated by Django 5.2.4 on 2026-01-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_general',
            field=models.BooleanField(default=False, help_text='Check if this subject is general (not tied to a course)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Select a course for this subject. Leave empty if general.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='subjects.course'),
        ),
    ]
