# Generated by Django 5.2.4 on 2026-01-01 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_is_general_alter_subject_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='subjects.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
