# Generated by Django 5.2.4 on 2026-01-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_general',
        ),
    ]
