# Generated by Django 5.2.4 on 2026-01-12 15:26

from django.db import migrations


def mark_general_subjects(apps, schema_editor):
    Subject = apps.get_model('subjects', 'Subject')
    for subject in Subject.objects.filter(course__isnull=True):
        subject.is_general = True
        subject.save()

class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_is_general_alter_subject_course_and_more'),
    ]

    operations = [
        migrations.RunPython(mark_general_subjects),
    ]
