# Generated by Django 5.2.4 on 2026-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0002_alter_bookmark_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_notes',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='notes.note'),
        ),
    ]
