# Generated by Django 5.2.4 on 2026-01-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreedomCommentReport',
        ),
    ]
