# Generated by Django 5.2.4 on 2026-01-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0014_alter_postlike_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
