# Generated by Django 5.2.4 on 2026-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_add_is_active_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
