# Generated by Django 5.2.4 on 2026-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_subject_alter_note_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin when rejecting a note', null=True),
        ),
    ]
