# Generated by Django 5.2.4 on 2026-01-06 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_commentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_reports', to='notes.comment'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_comment_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
