# Generated by Django 5.2.4 on 2026-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_rejection_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_removed',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='note',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
