# Generated by Django 5.2.4 on 2026-01-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_comment_parent_alter_comment_note'),
        ('notes', '0007_noteaction'),
    ]

    operations = [
    ]
