# Generated by Django 5.2.4 on 2026-01-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_comment_note_alter_commentreport_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
