# Generated by Django 5.2.4 on 2026-01-22 14:15

import apps.notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_notelike_notesave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[apps.notes.models.validate_file_type]),
        ),
    ]
