# Generated by Django 5.2.4 on 2026-01-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_comment_options_alter_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
