# Generated by manual edit on 2026-02-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0013_note_downloads"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
